config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Read all
    get '/tasks', to: 'tasks#index'

    # Create
    get '/tasks/new', to: 'tasks#new'
    post '/tasks', to: 'tasks#create'

    # Read one
    get '/tasks/:id', to: 'tasks#show', as: :show_task

    # Update
    get '/tasks/:id/edit', to: 'tasks#edit'
    patch '/tasks/:id', to: 'tasks#update', as: :task

    # Delete
    delete '/tasks/:id', to: 'tasks#destroy'

end


# # Read all
  # get '/restaurants', to: 'restaurants#index'

  # # Read one
  # get '/restaurants/:id', to: 'restaurants#show'

  # # Create
  # get '/restaurants/new', to: 'restaurants#new'
  # post '/restaurants', to: 'restaurants#create'

  # # Update
  # get '/restaurants/:id/edit', to: 'restaurants#edit'
  # patch '/restaurants/:id', to: 'restaurants#update'

  # # Delete
  # delete '/restaurants/:id', to: 'restaurants#destroy'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/toto.rb
class Toto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

    # GET /tasks
    def index
      @tasks = Task.all
    end

    # GET /tasks/:id
    def show
    end

    # GET /tasks/new
    def new
      @task = Task.new
    end

    # POST tasks
    def create
      task = Task.new(task_params)
      # task = Task.new(params[:task])
        # => will raise an ActiveRecord::ForbiddenAttributesError
      task.save

      redirect_to tasks_path
    end

    # GET /tasks/:id/edit
    def edit
      # @task = Task.find(params[:id])
    end

    # PATCH /tasks/:id
    def update
      # @task = task.find(params[:id])
      @task.update(task_params)

      redirect_to task_path(@task)
    end

    # DELETE /tasks/:id
    def destroy
      # @task = Task.find(params[:id])
      @task.destroy

      redirect_to tasks_path
    end

    private

    def task_params
      params.require(:task).permit(:title, :details)
    end

    def set_task
      @task = Task.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="formulaire">
  <%= form_for(@task) do |f| %>
    <%= f.text_field :title %>
    <%= f.text_field :details %>
    <%= f.submit %>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/index.html.erb
<!-- <div class= "container">
  <h1>Tasks list</h1>

  <% @tasks.each do |task| %>
    <h2><%= task.title %></h2>
    <p><%= task.details %></p>
    <input id="input" type="checkbox" <%= 'checked' if task.completed == true %>>

  <% end %>

</div> -->




<div class="container">
  <h1>My Tasks</h1>

    <% @tasks.each do |task| %>

      <input type="checkbox" name="details" <%= 'checked' if task.completed == true %>>

      <label for="details"><%= link_to task.title, show_task_path(task) %></label>
      <%= link_to task_path(task),
            method: :delete,
            data: { confirm: "Are you sure?" } do %>
            <i class="fab fab-bin" id="delete">Delete</i>
            <% end %>
    <% end %>

</div>

app/views/tasks/new.html.erb
<%= render 'form' %>

<p><%= link_to 'Back to list', tasks_path(@task) %></p>

app/views/tasks/show.html.erb
  <h2><%= @task.title %></h2>
  <div class='list'>
    <p><%= @task.details %></p>
  </div>
  <p><%= link_to 'Back to list', tasks_path(@task) %></p>